%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\nicoreacmp\Documents\Fracture Mechanics - Matlab\transfer\FAD\FAD\wide_plate_per_specimen_to_Arpi.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/29 14:45:12

%% Import the data
fname = 'C:\Users\nicoreacmp\Documents\Fracture Mechanics - Matlab\transfer\FAD\FAD\wide_plate_per_specimen_to_Arpi.xlsx';
[~, ~, wide_plate_per_specimen] = xlsread(fname,'Sheet1','A2:I135');
wide_plate_per_specimen(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),wide_plate_per_specimen)) = {''};

batch_name = wide_plate_per_specimen(:,1);
wide_plate_per_specimen = cell2mat(wide_plate_per_specimen(:,2:end));

%% Calculate the parameters for FAD curve
% Cut-off value:
Lr_max = (wide_plate_per_specimen(:,3) + wide_plate_per_specimen(:,4))./(2*wide_plate_per_specimen(:,3));
% Parameters for FAD curve suitable for materials that do not exhibit a yield discontinuity
Mu    = min(0.001 * wide_plate_per_specimen(:,2)./wide_plate_per_specimen(:,3), 0.6);
N     = 0.3 * (1 - wide_plate_per_specimen(:,3)./wide_plate_per_specimen(:,4));
% Parameters for FAD curve suitable for materials that do exhibit a yield discontinuity
Lamda = 1 + (wide_plate_per_specimen(:,2).*wide_plate_per_specimen(:,5))./wide_plate_per_specimen(:,3);
fLr = zeros(size(wide_plate_per_specimen,1),1);

for ii=1:size(wide_plate_per_specimen,1)
    % FAD curve suitable for materials that do not exhibit a yield discontinuity
    if wide_plate_per_specimen(ii,6) == 1
        if wide_plate_per_specimen(ii,8) <= 1
            fLr(ii,1) = (0.3 + 0.7*exp(-Mu(ii,1)*wide_plate_per_specimen(ii,8)^6))*(1 + 0.5*wide_plate_per_specimen(ii,8)^2)^(-0.5);
        elseif (wide_plate_per_specimen(ii,8) > 1) && (wide_plate_per_specimen(ii,8) < Lr_max(ii,1))
            fLr(ii,1) = (0.3 + 0.7*exp(-Mu(ii,1)*1))*((1 + 0.5*1)^(-0.5))*wide_plate_per_specimen(ii,8)^((N(ii,1)-1)/(2*N(ii,1)));
        elseif (wide_plate_per_specimen(ii,8) >= Lr_max(ii,1))
            fLr(ii,1) = 0;
        end
    elseif wide_plate_per_specimen(ii,6) == 2
        % FAD curve suitable for materials that do not exhibit a yield discontinuity
        if wide_plate_per_specimen(ii,8) < 1
            fLr(ii,1) = (1 + 0.5*wide_plate_per_specimen(ii,8)^2)^(-0.5);
        elseif wide_plate_per_specimen(ii,8) ==1
            fLr(ii,1) = (Lamda(ii,1) + 0.5./Lamda(ii,1))^(-0.5);
        elseif (wide_plate_per_specimen(ii,8) > 1) && (wide_plate_per_specimen(ii,8) < Lr_max(ii,1))
            fLr(ii,1) = ((Lamda(ii,1) + 0.5./Lamda(ii,1))^(-0.5))*(wide_plate_per_specimen(ii,8)^((N(ii,1)-1)/(2*N(ii,1))));
        elseif (wide_plate_per_specimen(ii,8) >= Lr_max(ii,1))
            fLr(ii,1) = 0;
        end
    else
        disp('Error: the FADtype flag must be 1 or 2')
    end
end